In [2]:
import numpy as np

In [26]:
# Задание 1
x =np.arange(12, 24)
print(x)

[12 13 14 15 16 17 18 19 20 21 22 23]


In [11]:
# Задание 2
x1= x.reshape(2, 6)
x2= x.reshape(6, 2)
x3= x.reshape(3, 4)
x4= x.reshape(4, 3)
x5= x.reshape(12, 1)
print(f'{x1} \n {x2} \n {x3} \n {x4} \n {x5}')


[[12 13 14 15 16 17]
 [18 19 20 21 22 23]] 
 [[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]] 
 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 
 [[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]] 
 [[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [16]:
# Задание 3
# Задание 2
x1= x.reshape(2, -1)
x2= x.reshape(6, -1)
x3= x.reshape(3, -1)
x4= x.reshape(-1, 3)
x5= x.reshape(-1, 1)
print(f'{x1} \n {x2} \n {x3} \n {x4} \n {x5}')

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]] 
 [[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]] 
 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 
 [[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]] 
 [[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [27]:
# Задание 4
# Нет
print(x.shape)
print(x5.shape)

(12,)
(12, 1)


In [29]:
# Задание 5
a = np.random.normal(0, 1, (3,4))
af = a.flatten()
print(a)
print(af)

[[ 0.3736923  -1.42289667 -0.76524756  0.58954658]
 [-0.50597318  1.75139444  0.87006087  0.7925993 ]
 [ 1.07567176  0.21742794  0.17935549  0.50549961]]
[ 0.3736923  -1.42289667 -0.76524756  0.58954658 -0.50597318  1.75139444
  0.87006087  0.7925993   1.07567176  0.21742794  0.17935549  0.50549961]


In [30]:
# Задание 6
b =np.arange(20, 0, -2)
print(b)

[20 18 16 14 12 10  8  6  4  2]


In [33]:
# Задание 7
# Разница в размерности массивов
c =np.arange(20, 0, -2).reshape(-1, 1)
print(c)
print(b.shape, c.shape)

[[20]
 [18]
 [16]
 [14]
 [12]
 [10]
 [ 8]
 [ 6]
 [ 4]
 [ 2]]
(10,) (10, 1)


In [39]:
# Задание 8
a = np.zeros((2, 2))
b = np.ones((3, 2))
c = np.vstack((a, b))
print(a)
print(b)
print(c)
print(c.size)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
10


In [46]:
# Задание 9
A =np.arange(0, 12).reshape(4, 3)
At = A.transpose()
B = np.dot(A, At)
print(A)
print(At)
print(B)
print(B.size, B.shape)
print(f'Не получится, det = {np.linalg.det(B)}')


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
16 (4, 4)
Не получится, det = 0.0


In [48]:
# Задание 10
np.random.seed(seed=42)

In [59]:
# Задание 11
c = np.random.randint(0, 16, 16)
print(c)

[15  7  8  3  0 13  0  9  3 11 13  6  1  2  0  4]


In [64]:
# Задание 12
C = c.reshape(4, -1)
D = B + 10* C
det_D = np.linalg.det(D)
rank_D = np.linalg.matrix_rank(D)
D_inv = np.linalg.inv(D)
print(C)
print(D)
print(det_D, rank_D)
print(D_inv)


[[15  7  8  3]
 [ 0 13  0  9]
 [ 3 11 13  6]
 [ 1  2  0  4]]
[[155  84 103  62]
 [ 14 180  86 212]
 [ 53 196 279 272]
 [ 42 142 212 342]]
648808800.0 4
[[ 7.34059094e-03 -5.62908518e-04 -4.52503110e-03  2.61704219e-03]
 [ 2.31192918e-04  7.90938717e-03  3.11869999e-03 -7.42517672e-03]
 [-1.47704532e-03 -5.85149277e-03  7.51524948e-03 -2.08203095e-03]
 [-8.18731189e-05  4.12355689e-04 -5.39776896e-03  6.97616925e-03]]


In [68]:
# Задание 13
D_inv[np.where(D_inv > 0)] = 1
D_inv[np.where(D_inv < 0)] = 0
E = np.where(D_inv, B, C)
print(D_inv)
print(E)

[[1. 0. 0. 1.]
 [1. 1. 1. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 1.]]
[[  5   7   8  32]
 [ 14  50  86   9]
 [  3  11 149   6]
 [  1 122   0 302]]
